# Project paths for the NF1 melanoma Xenium repository.
# Run scripts from the repository root.
PROJECT_ROOT <- normalizePath('.', winslash='/', mustWork=FALSE)
DATA_DIR <- file.path(PROJECT_ROOT,'data')
RAW_DIR <- file.path(DATA_DIR,'raw')
PER_CORE_DIR <- file.path(DATA_DIR,'per_core')
PROCESSED_DIR <- file.path(DATA_DIR,'processed')
METADATA_DIR <- file.path(DATA_DIR,'metadata')
RESULTS_DIR <- file.path(PROJECT_ROOT,'results')
FIGURES_DIR <- file.path(RESULTS_DIR,'figures')

# Main reproducible starting inputs. The user does NOT need to re-merge the
# million-cell dataset to run the manuscript's downstream Xenium analyses.
STARTING_OBJECT_FILE <- file.path(PROCESSED_DIR,'merged_obj_filtered.rds')
XENIUM_LIST_INPUT_FILE <- file.path(PROCESSED_DIR,'xenium_list.rds')

# Objects generated by the ordered pipeline.
ANNOTATED_OBJECT_FILE <- file.path(PROCESSED_DIR,'merged_obj_annotated.rds')
XENIUM_LIST_ANNOTATED_FILE <- file.path(PROCESSED_DIR,'xenium_list_annotated.rds')
MN_OBJECT_FILE <- file.path(PROCESSED_DIR,'merged_obj_annotated_with_meta_niche.rds')
XENIUM_LIST_MN_FILE <- file.path(PROCESSED_DIR,'xenium_list_with_meta_niche.rds')
MN_PUBLISHED_OBJECT_FILE <- file.path(PROCESSED_DIR,'merged_obj_annotated_with_meta_niche_published_reference.rds')
XENIUM_LIST_MN_PUBLISHED_FILE <- file.path(PROCESSED_DIR,'xenium_list_with_meta_niche_published_reference.rds')
REFERENCE_DIR <- file.path(DATA_DIR,'reference')
PRIVATE_PROVENANCE_DIR <- file.path(PROJECT_ROOT,'private_provenance')
RESPONSE_METADATA_FILE <- file.path(METADATA_DIR,'patient_treatment_response_annotation.csv')

# Optional upstream-provenance files. These scripts are supplied for documentation
# and future reconstruction but are NOT called by run_xenium_pipeline.R.
XENIUM_LIST_FILE <- file.path(PROCESSED_DIR,'xenium_list.rds')
MERGED_UNFILTERED_FILE <- file.path(PROCESSED_DIR,'merged_obj_unfiltered.rds')
MERGED_INTEGRATED_FILE <- file.path(PROCESSED_DIR,'merged_obj_integrated.rds')
CORE_ID_FIELD <- 'patient_id'       # change to a core-specific metadata field if available
HARMONY_GROUP_FIELD <- 'patient_id'
SCT_VARIABLE_FEATURES <- 3000L
CLUSTER_RESOLUTION <- 0.5

# Reported/final analysis parameters.
MIN_TRANSCRIPTS_PER_CELL <- 50L
MIN_CELLS_PER_CORE <- 5000L
N_PCS <- 30L
FINAL_CLUSTER_RESOLUTION <- 0.5
NEIGHBORHOOD_RADIUS_UM <- 40
MIN_NEIGHBORS <- 3L
N_META_NICHES <- 12L
META_NICHE_SEED <- 123L
META_NICHE_NSTART <- 25L

for (d in c(RAW_DIR,PER_CORE_DIR,PROCESSED_DIR,METADATA_DIR,REFERENCE_DIR,RESULTS_DIR,FIGURES_DIR)) {
  dir.create(d,recursive=TRUE,showWarnings=FALSE)
}
